apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rajnish-init/helm-charts
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true